server:
  port: 8080
  host: localhost

auth:
  jwt_secret: your-secret-key
  token_ttl: 3600

google_oauth:
  client_id: ""  # Will be loaded from GOOGLE_OAUTH_CLIENT_ID env var
  client_secret: ""  # Will be loaded from GOOGLE_OAUTH_CLIENT_SECRET env var
  redirect_uri: ""  # Will be loaded from GOOGLE_OAUTH_REDIRECT_URI env var
  scopes:
    - openid
    - email
    - profile